# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Flashtool(object):
    def setupUi(self, Flashtool):
        Flashtool.setObjectName("Flashtool")
        Flashtool.setEnabled(True)
        Flashtool.resize(906, 594)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Flashtool.sizePolicy().hasHeightForWidth())
        Flashtool.setSizePolicy(sizePolicy)
        Flashtool.setMinimumSize(QtCore.QSize(906, 594))
        Flashtool.setMaximumSize(QtCore.QSize(906, 594))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("flash.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Flashtool.setWindowIcon(icon)
        Flashtool.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(Flashtool)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 60, 851, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.loadBinaries = QtWidgets.QPushButton(self.centralwidget)
        self.loadBinaries.setGeometry(QtCore.QRect(630, 10, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadBinaries.setFont(font)
        self.loadBinaries.setObjectName("loadBinaries")
        self.pathToBinaries = QtWidgets.QLabel(self.centralwidget)
        self.pathToBinaries.setGeometry(QtCore.QRect(30, 20, 511, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathToBinaries.sizePolicy().hasHeightForWidth())
        self.pathToBinaries.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pathToBinaries.setFont(font)
        self.pathToBinaries.setObjectName("pathToBinaries")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(30, 100, 541, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setObjectName("treeView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(600, 90, 271, 451))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 101, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 61, 31))
        self.label_3.setObjectName("label_3")
        self.ECUSelect = QtWidgets.QComboBox(self.groupBox)
        self.ECUSelect.setGeometry(QtCore.QRect(100, 150, 151, 31))
        self.ECUSelect.setEditable(True)
        self.ECUSelect.setObjectName("ECUSelect")
        self.user_label = QtWidgets.QLabel(self.groupBox)
        self.user_label.setGeometry(QtCore.QRect(130, 50, 121, 31))
        self.user_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.user_label.setObjectName("user_label")
        self.tb_label = QtWidgets.QLabel(self.groupBox)
        self.tb_label.setGeometry(QtCore.QRect(130, 100, 121, 31))
        self.tb_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb_label.setObjectName("tb_label")
        self.StartBtn = QtWidgets.QPushButton(self.groupBox)
        self.StartBtn.setGeometry(QtCore.QRect(10, 400, 251, 41))
        self.StartBtn.setCheckable(False)
        self.StartBtn.setAutoDefault(False)
        self.StartBtn.setDefault(False)
        self.StartBtn.setFlat(False)
        self.StartBtn.setObjectName("StartBtn")
        Flashtool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Flashtool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 21))
        self.menubar.setObjectName("menubar")
        self.menuLogging = QtWidgets.QMenu(self.menubar)
        self.menuLogging.setObjectName("menuLogging")
        Flashtool.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Flashtool)
        self.statusbar.setObjectName("statusbar")
        Flashtool.setStatusBar(self.statusbar)
        self.actionOpen_Log = QtWidgets.QAction(Flashtool)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.actionOpen_Log.setFont(font)
        self.actionOpen_Log.setObjectName("actionOpen_Log")
        self.menuLogging.addAction(self.actionOpen_Log)
        self.menubar.addAction(self.menuLogging.menuAction())

        self.retranslateUi(Flashtool)
        QtCore.QMetaObject.connectSlotsByName(Flashtool)

    def retranslateUi(self, Flashtool):
        _translate = QtCore.QCoreApplication.translate
        Flashtool.setWindowTitle(_translate("Flashtool", "FlashTool"))
        self.loadBinaries.setText(_translate("Flashtool", "Load Binaries"))
        self.pathToBinaries.setText(_translate("Flashtool", "Binaries Path"))
        self.groupBox.setTitle(_translate("Flashtool", "Settings"))
        self.label.setText(_translate("Flashtool", "User"))
        self.label_2.setText(_translate("Flashtool", "Test Bench"))
        self.label_3.setText(_translate("Flashtool", "ECU"))
        self.user_label.setText(_translate("Flashtool", "userName"))
        self.tb_label.setText(_translate("Flashtool", "TBname"))
        self.StartBtn.setText(_translate("Flashtool", "START"))
        self.menuLogging.setTitle(_translate("Flashtool", "Logging"))
        self.actionOpen_Log.setText(_translate("Flashtool", "Open Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Flashtool = QtWidgets.QMainWindow()
    ui = Ui_Flashtool()
    ui.setupUi(Flashtool)
    Flashtool.show()
    sys.exit(app.exec_())

